### ISSUE TITLE
Somthing wrong...

### ISSUE THREAD

**Issue by wildfish-mail-ru** [jtq/clockworacle#1] opened 2015-10-17 11:34 UTC
For example...
![image](https://cloud.githubusercontent.com/assets/3693203/10558550/27e28218-74dc-11e5-936e-704206f6fae5.png)

**Comment by jtq** [comment] 2015-10-22 16:32
Ah - good catch! Sorry - I didn't see your post at first. That normally only happens when a QualityRequirement refers to a Quality that doesn't exist in the game data (which happens in the games config more than you might expect).

Just to help narrow down the cause in this case, did you build the mod-tools yourself from source, or download the pre-built zip file linked in the readme file?

**Comment by wildfish-mail-ru** [comment] 2015-10-22 19:41
No, it's not a my own mod-file. It's original json file from game.

**Comment by pickten** [comment] 2015-10-22 20:52
I think what he meant is whether you compiled them on your computer (so you'd have the most up to date version) or whether you downloaded the zip linked in the readme (so you'd have the most recent release), rather than whether you were using a mod you made.

**Comment by jtq** [comment] 2015-10-22 21:23
Thanks @pickten - that is indeed what I meant. ;-)

**Comment by jtq** [comment] 2015-10-22 21:44
Right - I think I've worked out what the problem is.

All items (Qualities, Events, Interactions, etc) in Sunless Sea are supposed to have their own unique IDs, so they can be uniquely identified (at least amongst all other objects of the same type).

I.e., there should only ever be one Quality with ID X, although it may(?) be possible to also have an Event with ID X without it causing confusion.

It appears that at some point (either in the Pigmote update, or previously and I just didn't notice) Failbetter have added some content, and it's duplicating the IDs of other content already in the game - at the very least there are multiple QualityRequirement objects with the same IDs.

For example there are two distinct QualityRequirement objects, both with the id 132575:
- One relates to  the "A meeting with the Pirate King" Event (ID #169576) and is a requirement for the "Objective: Seeking a Gift for the Pirate-King" Quality (#113395) to be exactly 3, while
- The other relates to the "Knock at the iron-studded gates..." Interaction (ID #129937) and is a requirement for the "Recent News" Quality (#109480) to be exactly 0.

**Comment by jtq** [comment] 2015-10-22 22:10
This means when mod-tools tries to read in the entire game file and create master lists of every type of object, it's:
1. Reading in the first QualityRequirement object
2. Attaching it to its parent Event object
3. Slotting it into place in the QualityRequirement master lookup table (indexed by ID)
4. Reading in the second QualityRequirement object
5. Attaching it to its parent Interaction object
6. Slotting it into place in the QualityRequirement master lookup table **and overwriting the existing object's entry**

Finally, when the system thinks it's loaded and created every object of every type from the game-json, it does a final pass over each of the master lookup tables, pulling out every object and "wiring it up" - converting all cases where one object refers to another by ID into an actual reference to the corresponding object in memory.

Because it's working down the master lookup table, the system finds and wires up the second QualityRequirement (attached to the Interaction), but there's no way it can find the first QualityRequirement (attached to the Event) because it's no longer in the table - it was overwritten by the second.

Then much later, when the system tries to render the list of events to the page it finds a QualityRequirement attached to the Event, tries to follow the memory-reference to the Quality object it represents (to do things like output its name and icon, instead of just an unmemorable ID number), and fails because the QualityRequirement object attached to the event was _never wired up_, so that memory reference doesn't point anywhere.

**Comment by jtq** [comment] 2015-10-22 23:50
I'm honestly not sure what to do for the best here, because it seems to be a bug in Failbetter's game-data.  I've added some code to the mod-tools to try to spot this happening and throw an error in the browser console (hit F12 in your browser and choose the "Console" tab, for non-web-devs), but I can't see any way to reasonably recover or elegantly handle this situation, because by definition the object IDs are supposed to uniquely and authoritatively identify every object in the game, and if you have two the same then there's just no way to reasonably differentiate between them.

I've pushed the [newer version](https://github.com/jtq/clockworacle/commit/07cbd19c63020ff34ab84daca64302c5764e44ef) of the code (with the warnings) up to Github, and rebuilt a new version of the mod-tools for you guys (same link as before, in the readme), and I'll log a ticket with Failbetter to hopefully fix this.

If they don't want to fix it then I'll investigate more radical solutions (for example, defining my own new IDs for duplicate objects), but I don't know what knock-on effects that might have on people trying to build mods for the game (since the mod-tools would technically be lying to them about the IDs of certain objects), so I'd rather not do that if we can convince Failbetter to fix the problem where it should be fixed - in the game json files.

**Comment by jtq** [comment] 2015-10-22 23:52
As a side note, thanks a lot for your efforts @wildfish-mail-ru  and @pickten - you're officially Clockwork Oracle's first bug-report.  Nice to know people are actually using it. ;-)

**Comment by pickten** [comment] 2015-10-23 00:12
Thanks! I don't actually use this, though. I do play SS, but I'm watching more because I am curious both about the mod tools and how you actually made this (decent-ish at js, familiar with jQuery, absolutely useless at other frameworks), so I'm watching this more out of curiosity.

**Comment by jtq** [comment] 2015-10-23 00:27
Heh, thanks - the UI's nothing fancy - I just hacked up a quick UI in a browser in vanilla javascript that allowed me to start poking around the game files, and carried on building it out from there.  It's actually not particularly well-architected as JS goes - I just hacked it together as quickly as possible to let me build the Clockwork Oracle mod, then reworked the architecture into CommonJS (Node) modules so I could build and package the mod on the command-line, and only later realised it might be useful to other people too.

If you know JS and are interested in poking around, there's actually a whole JS API to query the game-files in the mod-tools, accessible from the browser console - just check out the mod-tools (as per the README), drag-and-drop the game files onto the UI, then pop open your browser console and type `api` (enter).

All the parsed game objects are listed under `api.library`, organised by type, which is probably what you'd be most interested in - every object is parsed into a more convenient format, but the original (unmodified) game-data for every object is also always available in the <object>`.attribs` member variable.  Oh, and `api.whatIs(<id>)` is invaluable for helping you work out what sort of object some random number in the game data actually corresponds to.

You can look up objects by ID by using commands like `api.library.Event.id(143394)`, or you can query the libraries by providing a field name and a value - eg `api.library.Quality.query('Name', 'A Casket of Sapphires')`.  You can even query the raw (unparsed) game-data fields using `.queryRaw()` instead of `.query()`... but that's only really scratched the surface.  I really should get around to documenting it at some point.

**Comment by wildfish-mail-ru** [comment] 2015-10-23 09:12
Thanks for your work, @jtq. I with my friends using your prog for translating Sunless Sea on Russian language and your program very useful for this. :+1: 
We are waiting for next versions. :smile:

**Comment by jtq** [comment] 2015-10-24 20:16
Awesome - that's really cool.

To be honest I've scratched my own itch now and created the Clockwork Oracle mod, so I've kind of run out of ideas for further functionality to add to the mod-tools.

If there are any features you guys would like added to the mod-tools to help with translation of the game, just let me know...

**Closed as completed** 2016-02-15 11:39 UTC
